# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/8"

  config.vm.hostname = "relearning-laravel"

  config.vm.network :private_network, ip: '192.168.33.133'
  config.vm.network :forwarded_port, guest: 22, host: 13322, id: "ssh", auto_correct: true

  config.vm.synced_folder "../", "/home/vagrant/sync", type: "virtualbox",
                          :mount_options => ["dmode=777", "fmode=777"]

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--name", "relearning-laravel"]
    vb.memory = "2048"
  end

  config.vm.provision "docker"
end