version: '3'

services:
  mysql:
    build:
      context: ./mysql
      # Dockerfile に .env の変数を渡す
      args:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # MySQL設定
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # MySQLの文字コードとCollation
    #  https://qiita.com/tfunato/items/e48ad0a37b8244a788f6
    command: mysqld --character-set-server=utf8mb4 --character_set_client=utf8mb4 --character_set_connection=utf8mb4 --character_set_database=utf8mb4 --character_set_results=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
    restart: always
    networks:
      app_net:
        ipv4_address: 172.20.0.11

  php81_cli:
    build:
      context: ./php81-cli
    restart: always
    links:
      - mysql
    networks:
      app_net:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24